- name: EAP Compliance Check
  hosts: tag_Role_eap,eap
  gather_facts: yes
  become: yes

  tasks: 

  - name: Gather Instance per customers for ec2
    ec2_instance_facts:
    register: ec2_details
    when: "'ec2' is in group_names"
    run_once: yes
    delegate_to: localhost
    become: no

  - name: Gather Instance per customers for Azure
    azure_rm_resource_facts:
      resource_type: virtualmachine
    register: ec2_details
    when: "'azure' is in group_names"
    run_once: yes
    delegate_to: localhost
    become: no



  # - name: Is instance HA or not 


  # - name: 
